### ISSUE TITLE
Url is not working(404 Not Found )

### ISSUE THREAD

**Issue by dharmendravaishnav** [GoogleCloudPlatform/gradle-appengine-templates#29]
I have implemented this sample but i got error "404 not found".

https://android-app-backend.appspot.com/_ah/api/

This url is not working

**Comment by loosebazooka** [comment]
Do you have any other info?

**Comment by dharmendravaishnav** [comment]
This issue has been resolved.
I misunderstood the url part substitution of "android-app-backend" .
I was trying to replace this with the project number instead of project id.
