### ISSUE TITLE
'http://appengine.google.com/ns/1.0'  URI is not registered

### ISSUE THREAD

**Issue by seanpjanson** [GoogleCloudPlatform/gradle-appengine-templates#31]
Hi, 
when I generate 'module' using this example, in the generated 'appengine-web.xml', there is reference to http://appengine.google.com/ns/1.0, that reports "URI is not registered".
When I go to Settings | ...| Schemas and DTDs and add the url manually, the error changes to Resourcwe registered by this URI is not recognized"

Any idea what's wrong? Installation issue?

thanks, sean

**Comment by ludoch** [comment]
Which tool are you using? What do you add in the url manually? A link to the local schema file which is defined in the GAE SDK in the docs/config/ directory with the appengine-web.xsd file?

**Comment by seanpjanson** [comment]
@ ludoch:   I've been following this:
https://github.com/GoogleCloudPlatform/gradle-appengine-templates/tree/master/GcmEndpoints
using Android Studio 1.0.2, After choosing:
"App Engine Backend with Google Cloud Messaging"  (below 3rd picture of readme.md.)
the module gets generated. It includes the 'appengine-web.xml' mentioned above...
.

**Comment by seanpjanson** [comment]
I forgot to mention that I am on WIN7 OS.

**Comment by seanpjanson** [comment]
Sorry, this complaint might have been premature, it shows as an error in:
backend - src - main - webapp - WEB-INF 
which has probably nothing to do with the example I'm working on.

**Comment by seanpjanson** [comment]
I have disabled that lint error/warning with no noticeable impact. Everything is working. Closing.

**Comment by Brennan-M** [comment]
How do you disable the error/warning? I am getting the same problem?

**Comment by loosebazooka** [comment]
What IDE are you using?

**Comment by loosebazooka** [comment]
What version of Android Studio are you using?

**Comment by swarnameena** [comment]
if you're using android studio / inellij - go to project structure >> facets >> click on the + sign on the top and add Google App Engine Standard

Alternatively, go to Project Structure >> modules >> click on the + sign on the top and add Google App Engine Standard

This should resolve the error from showing and also auto-populates the valid entries for code-completion.
