### ISSUE TITLE
wrong types in AsyncTask

### ISSUE THREAD

**Issue by seanpjanson** [GoogleCloudPlatform/gradle-appengine-templates#32]
This is a minor typo in 
https://github.com/GoogleCloudPlatform/gradle-appengine-templates/tree/master/GcmEndpoints
README.MD file. In the '2.2. Registering devices with Google Cloud Messaging backend' section, there is an example code snippet, that starts:
class GcmRegistrationAsyncTask extends AsyncTask\<Context, Void, String\>  ....
it should be:
class GcmRegistrationAsyncTask extends AsyncTask\<Void, Void, String\>  ...
since doInBackground(Void... params) takes Void parameter(s).

**Comment by dustedrob** [comment]
I actually submitted an issue about the same thing a while ago but got ignored. This kind of  annoying details shouldn't clear Google's QA before releasing.
