### ISSUE TITLE
Add support for iOS client library generation

### ISSUE THREAD

**Issue by eliotstock** [GoogleCloudPlatform/gradle-appengine-templates#42]
... to HelloEndpoints. Or at least add documentation explaining how to generate them outside of AS/gradle. I see the discovery doc there in my build directory, but I have no idea what to do with it based on this.

**Comment by loosebazooka** [comment]
https://cloud.google.com/appengine/docs/java/endpoints/consume_ios

I guess we could link to this.

**Comment by eliotstock** [comment]
Yes, and update that page to make it clear where to find the discovery doc within the Gradle build perhaps.

**Comment by loosebazooka** [comment]
I see, I don't think that page has to know about gradle, I'll add it to the documentation here.

**Comment by redi-wassere** [comment]
Hey guys, whats the current status of this?

**Comment by loosebazooka** [comment]
updated the README on https://github.com/GoogleCloudPlatform/gradle-appengine-plugin
