### ISSUE TITLE
GcmEndpoints templates don't add GcmEndpoints/root/src/main/* to generated project

### ISSUE THREAD

**Issue by eliotstock** [GoogleCloudPlatform/gradle-appengine-templates#43]
I just went through the "New Module..." performance in AS and ended up with a module that only has a MyServlet.java source in it. None of the sources in GcmEndpoints/root/src/main are in the project.

I'm also at a loss as to what I need to add to my gradle file to get this into the build:

import com.google.android.gcm.server.Message;

**Comment by loosebazooka** [comment]
It appears you may have added the "Servlet" template and not the "GCM template". Could that be it?

**Comment by eliotstock** [comment]
Oh! Yes, sorry, that was it. Closing this.
