### ISSUE TITLE
sendMessage in MessagingEndpoint missing annotation

### ISSUE THREAD

**Issue by seanpjanson** [GoogleCloudPlatform/gradle-appengine-templates#52]
I'm no sure if it is an intentional omission, but my generated backend does not have 
  @ApiMethod(name = "sendMessage") 
annotation for
  public void sendMessage(@Named("message") String message)

It can also be seen in the screenshot with 3 red numbers '2' [here](https://github.com/GoogleCloudPlatform/gradle-appengine-templates/tree/master/GcmEndpoints).

![image](https://cloud.githubusercontent.com/assets/3613330/8889546/9f1136b4-329b-11e5-89c0-34c09a1775f5.png)

**Comment by loosebazooka** [comment]
I'm not sure what you mean?

The @ApiMethod annotation is optional https://cloud.google.com/appengine/docs/java/endpoints/annotations#apimethod_method-scoped_annotations

**Comment by seanpjanson** [comment]
I thought that the "sendMessage" method needs annotation (like   @ApiMethod(name = "sendMessage") in order to be accessible from an android app.

**Comment by seanpjanson** [comment]
BTW, I think that it the GCMEmdpoints template will need major change in relation to deprecation of
GoogleCloudMessaging.gcm.register() method. It is now in conflict with [this](https://developers.google.com/cloud-messaging/android/start)

**Comment by loosebazooka** [comment]
"all public, non static, non bridge methods in a class with an @Api annotation are exposed in the API, whether they have an @ApiMethod annotation or not"  So it will be added to the API with the @ApiMethod annotation.

With regards to this template being deprecated, we're working on an update, I will try to add a disclaimer or something to this tutorial.

**Comment by seanpjanson** [comment]
Thank you, did not know that, sorry. Closing.
