### ISSUE TITLE
Problem after including GcmRegistrationAsyncTask class

### ISSUE THREAD

**Issue by palsoft333** [GoogleCloudPlatform/gradle-appengine-templates#53]
Hi,
I'm pretty new to Android Studio and Android develpoing, but I was going by this step-by-step tutorial and stucked at copypasting the GcmRegistrationAsyncTask class into the MainActivity. What did i do wrong? Should I add some dependecies outside those created automaticaly by the script?

Thank you very much!
![screenshot](https://cloud.githubusercontent.com/assets/13525347/8912733/059def76-3495-11e5-8370-36162001c6f0.png)

**Comment by loosebazooka** [comment]
You probably need to import all those classes. Android Studio/Intellij should auto suggest those for you.

**Comment by palsoft333** [comment]
Thanks, found out how finally :)
