### ISSUE TITLE
Registration isn't recognized in AsyncTask example.

### ISSUE THREAD

**Issue by ItamarShDev** [GoogleCloudPlatform/gradle-appengine-templates#59]
When trying to use the AsyncTask example, the Registration object is not recognized and Android Studio cant import it.
Am I missing something?
Using it with:
minSdkVersion 17
targetSdkVersion 23

**Comment by loosebazooka** [comment]
Try doing a project build to trigger copying the client libraries?

**Comment by ItamarShDev** [comment]
Building the Project didn't help
AS still throw error on Registration object "Cannot Resolve Symbol"
Is there any substitution to this object?
Maybe is deprecated?
Can I use any other method?

**Comment by ItamarShDev** [comment]
FIXED
thenks
