### ISSUE TITLE
Cleaning up temporary files for module default...

### ISSUE THREAD

**Issue by LadwaAditya** [GoogleCloudPlatform/gradle-appengine-templates#72]
Deploying to Google app engine stops at

Beginning interaction for module default...
0% Created staging directory at: 'C:\Users\Aditya\AppData\Local\Temp\appcfg5965290518124966335.tmp'
5% Scanning for jsp files.
20% Scanning files on local disk.
25% Initiating update.
28% Cloning 2 static files.
31% Cloning 14 application files.
40% Uploading 0 files.
52% Initializing precompilation...
90% Deploying new version.
95% Will check again in 1 seconds.
98% Will check again in 2 seconds.
99% Will check again in 4 seconds.
99% Closing update: new version is ready to start serving.
99% Uploading index definitions.

Update for module default completed successfully.
Success.
Cleaning up temporary files for module default...

After this there is no progress for more than an  hour

OS : Windows 10
Android studio 1.5.1

**Comment by TurhanOz** [comment]
Hi there, same here.
I tried with 2 different accounts, being stuck at _Cleaning up temporary files for module default..._ with no progress. 
Cheers

**Comment by thinkocapo** [comment]
I'm getting the same issue. Did you find a solution yet? I saw this issue on a few forums and no one had a solution. On a google dev forum, a google employee responded and said its due to system maintenance and pretty much to "try again later". Not sure what to do.

**Comment by thinkocapo** [comment]
here is what I'm talking about, https://issuetracker.google.com/issues/35895599 from 2015

**Comment by evankanderson** [comment]
The log above is not a failure to deploy -- you can see that it prints

> Closing update: new version is ready to start serving.

and

> Update for module default completed successfully.
> Success.

If you look at [this (old fork, the code.google.com version was shut down)](https://github.com/CyboLabs/googleappengine/blob/master/java/src/main/com/google/appengine/tools/admin/AppCfg.java#L199), you can see that the recursive cleanup is the last step of deployment. You can [see that the application called `cleanStagingDirectory()`](https://github.com/CyboLabs/googleappengine/blob/master/java/src/main/com/google/appengine/tools/admin/AppCfg.java#L336), which calls the following fairly simple code:

```
  /** deletes the staging directory, if one was created. */
  @Override
  public void cleanStagingDirectory() {
    if (stageDir != null) {
      recursiveDelete(stageDir);
    }
  }

  /** Recursive directory deletion. */
  public static void recursiveDelete(File dead) {
    String[] files = dead.list();
    if (files != null) {
      for (String name : files) {
        recursiveDelete(new File(dead, name));
      }
    }
    dead.delete();
  }
```

The AppCfg java process might be hanging for one of two reasons at this point:

1. The `File.delete()` in `recursiveDelete` might be hanging or attempting to delete a large number of files.
1. It's possible that the process ended up spawning a background thread and [did not mark it as daemon](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setDaemon(boolean)). You could determine this by getting a stack dump of the running AppCfg process.
