### ISSUE TITLE
Tag Mismatch

### ISSUE THREAD

**Issue by abhilash1in** [GoogleCloudPlatform/gradle-appengine-templates#88]
I get the following error after adding an App Engine Java Endpoints Module on Android Studio 2.3
> Error:Could not resolve all files for configuration ':backend:appengineSdk'.
> Could not download appengine-java-sdk.zip (com.google.appengine:appengine-java-sdk:1.9.42)
   > Could not get resource 'https://jcenter.bintray.com/com/google/appengine/appengine-java-sdk/1.9.42/appengine-java-sdk-1.9.42.zip'.
      > Could not GET 'https://jcenter.bintray.com/com/google/appengine/appengine-java-sdk/1.9.42/appengine-java-sdk-1.9.42.zip'.
         > Tag mismatch!`

Note: I am connected to the Internet. I can browse in a regular fashion.

**Comment by aya-salama1989** [comment]
I am facing the same issue, found any solutions yet?

**Comment by MohammedShalan** [comment]
Anyone have a solution for this issue ?!

**Comment by loosebazooka** [comment]
Perhaps try a different version of the sdk `1.9.54` is the latest. I haven't seen this error.

**Comment by MohammedShalan** [comment]
How to install it manually or what the path of it ?!

**Comment by ardanees-jatali** [comment]
this issue is due to the network setting. Change your ISP in other words try to connect to other network and try.

**Comment by patflynn** [comment]
those download links work for me.

**Comment by patflynn** [comment]
as an alternative you can try downloading from:
https://cloud.google.com/appengine/docs/standard/java/download

and configuring APPENGINE_HOME env variable or the system property appengine.sdk.root to point to wherever you installed the sdk.

**Comment by Magedsaad** [comment]
last comment is solved this issue
